# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- dev

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '5.0.x'
    includePreviewVersions: true

- task: UseDotNet@2
  inputs:
    packageType: 'runtime'
    version: '3.1.x'
    includePreviewVersions: true

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    arguments: '--configuration $(buildConfiguration) --version-suffix $(OrchardBuildNumber) /nodeReuse:false /p:TreatWarningsAsErrors="false"'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: 'test/OrchardCore.Tests/OrchardCore.Tests.csproj'
    arguments: '-c $(buildConfiguration) --no-restore --no-build'

- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    packagesToPack: '**/*.csproj'
    restoreArguments: no-restore
    nobuild: true
    versioningScheme: 'byBuildNumber'