# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
    include:
    - dev
    - master

pool:
  vmImage: 'ubuntu-latest'

variables:
  nugetPackages: $(Pipeline.Workspace)/.nuget/packages
  buildConfiguration: 'Release'

steps:
- task: Cache@2
  inputs:
    key: 'nuget | "$(Agent.OS)" | !**/bin/**'
    restoreKeys: |
       nuget | "$(Agent.OS)"
    path: $(nugetPackages)
  displayName: Cache NuGet packages

- task: DotNetCoreCLI@2
  displayName: 'dotnet restore'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration $(BuildConfiguration) --no-restore'

- task: DotNetCoreCLI@2
  displayName: 'dotnet test'
  inputs:
    command: 'test'
    projects: 'test\OrchardCore.Tests\OrchardCore.Tests.csproj'
    arguments: '--configuration $(BuildConfiguration) --no-build'


- task: DotNetCoreCLI@2
  displayName: 'Pack'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/dev'))
  inputs:
    command: 'pack'
    packagesToPack: 'src/**/*.csproj'
    versioningScheme: 'byBuildNumber'

- task: DotNetCoreCLI@2
  displayName: 'Push to Feed'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/dev'))
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: 'f916b128-58e5-458b-af5f-57086c37ee0c'