# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- dev

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  inputs:
    version: '5.0.x'
    includePreviewVersions: true

- task: UseDotNet@2
  inputs:
    version: '3.1.x'
    includePreviewVersions: true
    packageType: runtime

- script: dotnet build --configuration $(buildConfiguration) --version-suffix $(OrchardBuildNumber) /nodeReuse:false /p:TreatWarningsAsErrors="false"
  displayName: 'Build $(buildConfiguration)'

- script: dotnet test -c $(buildConfiguration) --no-restore --no-build ./test/OrchardCore.Tests/OrchardCore.Tests.csproj
  displayName: 'Unit Tests'

- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    packagesToPack: '**/*.csproj'
    restoreArguments: no-restore
    nobuild: true
    versioningScheme: 'byBuildNumber'