# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
    include:
    - dev
    - master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: 'dotnet restore'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration $(BuildConfiguration) --no-restore'

- task: DotNetCoreCLI@2
  displayName: 'dotnet test'
  inputs:
    command: 'test'
    projects: 'test\OrchardCore.Tests\OrchardCore.Tests.csproj'
    arguments: '--configuration $(BuildConfiguration) --no-build'


- task: DotNetCoreCLI@2
  displayName: 'Pack'
  condition: and(succeeded(), startsWith(variables['build.sourceBranch']))
  inputs:
    command: 'pack'
    packagesToPack: 'src/**/*.csproj'
    versioningScheme: 'byEnvVar'
    versionEnvVar: 'PACKAGE_VERSION'

- task: DotNetCoreCLI@2
  displayName: 'Push to Feed'
  condition: and(succeeded(), startsWith(variables['build.sourceBranch']))
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: 'f916b128-58e5-458b-af5f-57086c37ee0c'